development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: TweetStreamASE@gmail.com
  :password: TweetStreamASE0
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: TweetStreamASE@gmail.com
  :password: TweetStreamASE0
  :enable_starttls_auto: true
